### ISSUE TITLE
Cannot deserialize

### ISSUE THREAD

**Issue by vasily-kirichenko** [Zaid-Ajaj/Fable.Remoting#102]
The API:

```fsharp
[<RequireQualifiedAccess>]
type LogError =
    | NoLogsDir
    | NoLogFile
    | IOError of string

type LogEntry =
    { TimeLocal: DateTime
      Level: string
      Message: string }

type AppName = string
type HostName = string
type PID = int
type ErrorsOnly = bool

type Api =
        { GetLog: HostName * AppName * PID * ErrorsOnly -> Async<Result<LogEntry list, LogError>> }
```
The error:
> Cannot convert ["JObject",{"comparer":{},"tree":["MapOne","Ok",["JArray",[["JObject",{"comparer":{},"tree":["MapNode","Level",["JString","INFO"], "MapEmpty",["MapNode","Message",["JString"," [Logger, 13] - Connecting to <....>"],...}] to ["Any",null]

**Comment by Zaid-Ajaj** [comment]
Hello @vasily-kirichenko, this is a duplicate of #101 where metadata of `Result<'a>` isn't available on the client side of things (the `[Any, null]` bit of the error message) 

please update Fable compiler to latest v2.1.4, this should have been fixed since v2.1.2

**Comment by vasily-kirichenko** [comment]
It's helped, thanks! :)

**Comment by alfonsogarciacaro** [comment]
Ups, sorry for breaking the code of so many people in the 2.1 release! 😅

**Comment by Zaid-Ajaj** [comment]
Don't worry about it @alfonsogarciacaro, if the fix it simply to update to latest Fable then it is no big deal 😘
