### ISSUE TITLE
expression expected to have type readystate

### ISSUE THREAD

**Issue by jfrank-summit** [Zaid-Ajaj/Fable.Remoting#123]
I'm getting this error while trying to mess around with the Fable 3.0 upgrades. I took out remoting and everything (but remoting, of course) works. Any ideas? Do you need more info? Thanks!

ERROR in ./.fable/Fable.Remoting.Client.5.3.0-beta/Http.fs
Module Error (from ./node_modules/fable-loader/index.js):
C:/repos/VSTS/Summit/Summit.CRM/.fable/Fable.Remoting.Client.5.3.0-beta/Http.fs(57,19): (57,20) error FSHARP: This expression was expected to have type
    'ReadyState'    
but here has type
    'int'     (code 1)
 @ ./.fable/Fable.Remoting.Client.5.3.0-beta/Proxy.fs 9:0-86 159:81-98 159:99-110 159:120-128 159:142-146 159:160-177 159:178-189 159:199-202 174:64-68 174:69-80 174:90-98 174:112-116 174:130-134 174:135-146 174:156-159
 @ ./.fable/Fable.Remoting.Client.5.3.0-beta/Remoting.fs

**Comment by Zaid-Ajaj** [comment]
Hello Jeremy, this error occurs if you are Fable.Browser.XMLHttpRequest version 1.0 instead of pre-release version that Table.Remoting.Client depends on. Can you please check if that is the case? 

Remoting is still in beta because Fable 3.0 just went stable yesterday so I will publish a stable release this weekend

**Comment by jfrank-summit** [comment]
Thanks for the quick reply! The only version I see is 1.0 (don't see a pre-release) and still not working but I understand it's beta. Thanks for your hard work, looking forward to stable versions!

**Comment by jfrank-summit** [comment]
I got it to work. 1.0 is newer than the Fable.Browser.XMLHttpRequest 1.0.0-alpha-001. I had to reference the alpha version directly. Thanks!

**Comment by Zaid-Ajaj** [comment]
No problem! Indeed the version `1.0.0-alpha-001` is the pre-release version.

I think you can even remove the Fable.Browser.XMLHttpRequest reference all together from your packages and the right package will be automatically downloaded because it is a transitive dependency of Fable.Remoting.Client

**Comment by Zaid-Ajaj** [comment]
Published stable Remoting.Client v5.3.0, should be available soon when nuget finishes validating/indexing etc.
