### ISSUE TITLE
Singe Case Union = Blank

### ISSUE THREAD

**Issue by jfrank-summit** [Zaid-Ajaj/Fable.Remoting#124]
I may be doing something wrong but this worked before the Fable 3 upgrades. When I send a single case union over remoting it shows up blank. 
The lines with dates are generated by "getOrgList", which is pulling from a database, converting to domain and returning that. See below:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8095/api/IOrgApi/getOrgList
4/20/2019 5:14:07 PM: from db: seq [{Id = cf0bb3a2-cde3-4cd7-b85d-6986c570ab34;
      OrgName = "Summit";}]
4/20/2019 5:14:07 PM: getting: Some {Id = cf0bb3a2-cde3-4cd7-b85d-6986c570ab34;
      OrgName = Name "Summit";}
returning: [{Id = cf0bb3a2-cde3-4cd7-b85d-6986c570ab34;
  OrgName = Name "Summit";}]
Fable.Remoting: Returning serialized result back to client
[{"Id":"cf0bb3a2-cde3-4cd7-b85d-6986c570ab34","OrgName":{}}]

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.7973ms 200 application/json; charset=utf-8
```
Thanks!

**Comment by Zaid-Ajaj** [comment]
Hello there,
Can you please provide more information: How does your Single Case Union type look like and how the protocol function is defined?

Thanks

**Comment by jfrank-summit** [comment]
As I was pulling the code together I decided to try something: I had Name as private with a public constructor. When I took off private, it worked. Still a little strange to me as it worked outside of the local context in other places but I'll confess to hacking this together so who knows!

**Comment by Zaid-Ajaj** [comment]
Private fields are not serialization-friendly, Fable.Remoting expects to work with public fields in records

**Comment by jfrank-summit** [comment]
makes sense.Thank!
