### ISSUE TITLE
Server returns empty response when handling of the request takes long

### ISSUE THREAD

**Issue by kMutagene** [Zaid-Ajaj/Fable.Remoting#125]
I am not sure if this is the right place to ask this question, but i am running out of ideas.

I am using Fable.Remoting in a SAFE stack application (using suave on the server side). I am sending a post request than contains an array of data, which is handled by the server. The server then applies a function to the data and returns the result. Depending on the size of the input array (an array of size 2 works charmless, an array of size 12 fails), The client reports the following error:

![image](https://user-images.githubusercontent.com/21338071/58701794-39da6500-83a4-11e9-8dbd-d6c0046e31ff.png)

What i find strange is, that after the server actually applied the function to all the data, the logging output is the following:

![image](https://user-images.githubusercontent.com/21338071/58701844-668e7c80-83a4-11e9-9f05-33fffcff7739.png)

So the function is applied successfully, but the error above is sent before the actual response. I would imagine this has to do something with timeout settings? 

Any help would be greatly appreciated!

**Comment by Zaid-Ajaj** [comment]
Hello there @kMutagene, 

Fable.Remoting doesn't do anything with respect to timeouts. The error returned says: `"Http error from server occured while making request to /api/ITargetPApi/FastaFileRequest"` This means that an *exception* has been thrown on the server! The response text is empty because you most likely haven't propagated the server-side errors to the client. 

Please see the [Error Handling](https://zaid-ajaj.github.io/Fable.Remoting/src/error-handling.html) section where it is explained how you can log the error and/or propagate error information back to the client (which will be present in `responseText`)

Please let me know if anything is unclear, thanks

**Comment by kMutagene** [comment]
Hi @Zaid-Ajaj , 

thank you for the quick response. While i may not fully understand the error handling yet, this should propagate basically all errors right?

    let errorHandler (ex: Exception) (routeInfo: RouteInfo<HttpContext>) : ErrorResult = 
        // do some logging
        printfn "Error at %s on method %s" routeInfo.path routeInfo.methodName
        // decide whether or not you want to propagate the error to the client
        match ex with
        | _ ->  Propagate {errorMsg = (sprintf "%s" ex.Message)}

**Comment by Zaid-Ajaj** [comment]
Yes, your response text will be 
```json
{  
  "responseText":  "{ \"errorMsg\": \"exception message\" }"
}
``` 
if you just want the exception message then use this `errorHandler`:
```fs
let errorHandler (ex: Exception) (routeInfo: RouteInfo<HttpContext>) : ErrorResult = 
    // do some logging
    printfn "Error at %s on method %s" routeInfo.path routeInfo.methodName
    Propagate (sprintf "%s" ex.Message)
```
Then the response will be
```json
{  
  "responseText":  "exception message"
}
```
Don't forget to use the `errorHandler` in your API definition:
```fs
let webApp = 
    Remoting.createApi()
    |> Remoting.withErrorHandler errorHandler // <- this line
    |> Remoting.fromValue musicStore
```

**Comment by kMutagene** [comment]
Again, thanks for the help!

This is my code:
```

type CustomError = { errorMsg: string }

let errorHandler (ex: Exception) (routeInfo: RouteInfo<HttpContext>) : ErrorResult = 
    // do some logging
    printfn "Error at %s on method %s" routeInfo.path routeInfo.methodName
    // decide whether or not you want to propagate the error to the client
    match ex with
    | _ ->  Propagate {errorMsg = (sprintf "%s" ex.Message)}

let webApi =
    Remoting.createApi()
    |> Remoting.withRouteBuilder Route.builder
    |> Remoting.withDiagnosticsLogger (fun x -> if x.Length < 10000 then printfn "%s" x else (printfn "omitting some of the serialized result [length is above 10000 characters]...\r\n%s" x.[0..10000]))
    |> Remoting.withErrorHandler errorHandler
    |> Remoting.fromValue targetPApi
    |> Remoting.buildWebPart
```
However, the response text is still empty:

![image](https://user-images.githubusercontent.com/21338071/58712670-4e792600-83c1-11e9-96cf-0daa8610b83e.png)

I enabled verbose logging of suave. This reports the following error:

![image](https://user-images.githubusercontent.com/21338071/58712724-71a3d580-83c1-11e9-838d-ce5a7207fb7e.png)

So if i understand this right, the seems not to be related to the api but rather an internal suave error? If so i think this issue can be closed as it seems not to be related to Fable.Remoting

**Comment by Zaid-Ajaj** [comment]
Hmm this is strange, I was checking the errors returned from the server and it seems the error you are seeing is coming from a very old release of `Fable.Remoting.Client`, are you using Fable 1.x with Fable.Remoting.Client `v3.3.1`? It is not guaranteed that this is version works with latest `Fable.Remoting.Suave`. Actually I am pretty sure it will go wrong... 

Can you please list the versions of Fable.Remoting.* that you are using? Is it correct that you are using Fable 1.x using `dotnet fable`?

**Comment by kMutagene** [comment]
This is my paket.dependencies file:
```

group Server
    source https://api.nuget.org/v3/index.json
    framework: netcoreapp2.2
    storage: none

    nuget FSharp.Core
    nuget Suave 2.5.0.0
    nuget Fable.Remoting.Suave

group Client
    source https://api.nuget.org/v3/index.json
    framework: netstandard2.0
    storage: none

    nuget Fable.Core ~> 2
    nuget Fable.Elmish ~> 2
    nuget Fable.Elmish.Debugger ~> 2
    nuget Fable.Elmish.React ~> 2
    nuget Fable.Elmish.HMR ~> 2
    nuget Fable.React ~> 4
    nuget Fable.Remoting.Client ~> 4
    nuget Fulma
    nuget Fable.FontAwesome.Free

group Build
    source https://api.nuget.org/v3/index.json
    framework: netstandard2.0
    storage: none

    nuget FSharp.Core 4.3.4 // https://github.com/fsharp/FAKE/issues/2001
    nuget Fake.Core.Target
    nuget Fake.DotNet.Cli
    nuget Fake.IO.FileSystem
```

**Comment by Zaid-Ajaj** [comment]
Hmm alright, these versions are actually pretty recent (although not latest) 🤔 and they *should* work properly, so it is the error coming from Suave

**Comment by kMutagene** [comment]
Okay i will ask there if someone can explain the cause of this error then, thank you very much for your help!
