### ISSUE TITLE
How do you do streaming

### ISSUE THREAD

**Issue by tforkmann** [Zaid-Ajaj/Fable.Remoting#136]
Hi there,

how can I write to a stream with Fable.Remoting?
I would like to stream a excel file.

My old Giraffe code looks like that:

```
let getExcel (ctx:HttpContext) =
    (fun (guid:string) ->
        task {
            // get from blob storage
            let guidStr = guid + ".xlsx"
            let! buff = downloadExcelWbFromBlob guidStr  //new FileStream (path,FileMode.Open, FileAccess.Read)
            let stream = new MemoryStream(buff)
            let l = int stream.Length
            stream.Position <- int64 0
            ctx.Response.Headers.["Content-Length"] <- StringValues(l.ToString())
            ctx.Response.Headers.["Content-Type"] <- StringValues("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            ctx.Response.Headers.["Content-Disposition"] <- StringValues(sprintf "attachment;filename=%s_Export.xlsx" guid)
            return! ctx.WriteStreamAsync
                true // enableRangeProcessing
                stream
                None // eTag
                None // lastModified
        })
```

Any help would be appreciated.

**Comment by kerams** [comment]
Remoting is just one handler, so you can compose it with yours too. This is working for me:
```fsharp
let accountApiHandler =
    Remoting.createApi ()
    |> Remoting.withRouteBuilder Route.builder
    |> Remoting.fromContext createApi
    |> buildHttpHandler

let fileUploadHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let formFeature = ctx.Features.Get<IFormFeature>()
            let! form = formFeature.ReadFormAsync System.Threading.CancellationToken.None
            use s = new StreamReader(form.Files.[0].OpenReadStream())
            s.ReadToEnd() |> printfn "%s"
            return! next ctx }

let upl = route "/api/upload" >=> fileUploadHandler

// composing the two
app.UseGiraffe (choose [ accountApiHandler; upl ])
```

**Comment by tforkmann** [comment]
Ok thanks!

I'm using Saturn though. Do you know how to plug them together with Saturn?

**Comment by kerams** [comment]
Sorry, haven't tried Saturn myself.

**Comment by tforkmann** [comment]
Ok just found it out:

you just have to add them together like this;

´let octoBusApiHandler : HttpHandler =
    Remoting.createApi()
    |> Remoting.withRouteBuilder Route.builder
    |> Remoting.fromContext octobusApi
    |> Remoting.buildHttpHandler

let webApp = router {
    getf "/api/GETEXCEL/%s" ExcelExport.getExcel

}
let app = application {
    url ("http://0.0.0.0:" + port.ToString() + "/")
    use_router webApp
    use_router octoBusApiHandler
 }´

**Comment by Nhowka** [comment]
Checking the code, `use_router` accepts a single router, overwriting the first one. You can add them together using the `choose` function before passing it to `use_router`.

**Comment by tforkmann** [comment]
```use_router (choose [webApp;octoBusApiHandler]) ```

**Comment by tforkmann** [comment]
thanks guys!
:D

**Comment by Zaid-Ajaj** [comment]
Hello Tim! 

Streaming in the sense of streaming videos or other kinds of media is not supported via Fable.Remoting but in your case, file download *is* supported: remote functions that return `Async<byte[]>` are optimized and are returned via the response stream as raw binary data with content type `application/octet-stream` so your server side function becomes:
```fs
let downloadExcel (guid: string) : Async<byte[]> = 
  async {
    let fileName = guid + ".xlsx"
    let! content = Async.AwaitTask (downloadExcelWbFromBlob fileName)
    return content
  }
```
That's it! Fable.Remoting will turn stream the binary data to the client directly without going through the JSON serialization process. 

On the client-side however, you have to do more work because once you get the `byte[]` from the server, you have to "manually" download it:

- Create a `Blob` from the `byte[]`
- Turn the `Blob` into a data url object
- Add the data url to a dummy anchor `<a></a>` element
- Click the element (without adding it to screen)
- Remove the element
 
```fs
open Fable.Core
open Fable.Core.JsInterop
open Browser.Dom 

[<Emit("new Blob([$0.buffer], { 'type': $1 })")>]
let createBlobFromBytes (bytes: byte[]) (contentType: string) : Browser.Types.Blob = jsNative

[<Emit("window.URL.createObjectURL($0)")>]
let createObjectUrl (blob: Browser.Types.Blob) : string = jsNative

let downloadFile (guid: string) =
    async {
        let! fileContents = Server.api.downloadFile guid
        let contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        let blob = createBlobFromBytes fileContents contentType
        let dataUrl = createObjectUrl blob
        let anchor = document.createElement "a"
        anchor?style <- "display: none"
        anchor?href <- dataUrl
        anchor?download <- sprintf "%s-Excel.xlsx" guid
        anchor.click()
        // clean up
        anchor.remove()
    }
```
