### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by brettrowberry** [Zaid-Ajaj/Fable.Remoting#137]
Fable.Remoting is awesome in Giraffe and Saturn. Would it be possible to make it work with Azure Functions? I don’t have any clue what this would look like, but having API in Azure Functions and a static site as Blobs is a really cheap way to run a website.

**Comment by Zaid-Ajaj** [comment]
Hello Brett! 

Remoting can be used with Azure Functions as a backend the same way any Giraffe or Saturn application works in Azure Functions, after all, you only get a `HttpHandler` and wherever you host it is up to you. 

Here are a couple of applications that use Azure Functions with Remoting:
  - [Fantomas UI](https://gitlab.com/jindraivanek/fantomas-ui)
  - [Yobo](https://github.com/Dzoukr/Yobo)

Resources: 
 - [Introducing Saturn on Functions](https://medium.com/lambda-factory/introducing-saturn-on-functions-fa2338d431de)
 - [Giraffe.AzureFunctions](https://github.com/giraffe-fsharp/Giraffe.AzureFunctions)
