### ISSUE TITLE
What types are Serializable

### ISSUE THREAD

**Issue by G5Becks** [Zaid-Ajaj/Fable.Remoting#138]
Hi, sorry if this question is already answered elsewhere, but I am new to Fable/F# and Fable.Remoting. I read the docs and could not find any specific information regarding what is and is not serializable when using this library. If it is documented elsewhere, could you please provide a reference.

Thanks.

**Comment by Zaid-Ajaj** [comment]
Hello there @G5Becks, It is indeed not documented, usually you will find the supported types in [this test file](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.IntegrationTests/Shared/SharedTypes.fs) where I define the shared types I test this library with. In summary, 
 - All primitve types (among unit/byte[]/DateTime/DateTimeOffset/bigint/decimal/int64)
 - Optional types 
 - Tuples
 - Result types
 - Any record type (generic, non-generic)
 - Anonymous records (except for weird case at #132)
 - Any discriminated union (generic, non-generic, single case, whatever)
 - F# arrays, maps, sets, seq, lists, dictionary resize array
 - Any combination of the above 

What is not supported is things like multi-dimensional arrays, types in System.Numerics are not all supported such as Vector, Quaternions, matrices. Lastly, classes are not supported. 

If you find something that doesn't work and you think it should be supported, then file an issue so we can discuss it :smile:

**Comment by G5Becks** [comment]
Hi, That's all I needed to know! thanks a lot for the fast response.
