### ISSUE TITLE
Invalid cast invoking function "Map<int * int,int> -> Async<bool>"

### ISSUE THREAD

**Issue by markCompostional** [Zaid-Ajaj/Fable.Remoting#145]
See 

https://github.com/markCompostional/ElmishRemotingMapIssue

description of issue, code and instruction of how to reproduce there.

server reports

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:8085/api/ICounterApi/setMap application/json; charset=UTF-8 13
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Fable.Remoting.Server.DynamicRecord.createArgsFromJson$cont@132-1(RecordFunctionInfo func, FSharpOption`1 logger, Type input, JToken parsedJson, Unit unitVar)
   at Fable.Remoting.Server.DynamicRecord.tryCreateArgsFromJson(RecordFunctionInfo func, String inputJson, FSharpOption`1 logger)

**Comment by Zaid-Ajaj** [comment]
Hello @markCompostional, thanks a lot for the detailed issue and for the repository to reproduce the problem, I will look into it ASAP :smile:

**Comment by markCompostional** [comment]
I’ve got a workaround using just list, so no panic.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Zaid-Ajaj** [comment]
Hello @markCompostional, this should be fixed if you update your Giraffe adapter from v3.10.0 -> v3.11.0
```
paket update Fable.Remoting.Giraffe --group Server
```
I tried it in the repro you posted and no errors occur, can you confirm? Please re-open the issue if the problem persists :smile:

**Comment by markCompostional** [comment]
Let me try

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by markCompostional** [comment]
Works for me!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Zaid-Ajaj** [comment]
Awesome 🎉 thanks for confirming
