### ISSUE TITLE
Is it possible to receive request headers and/or send response headers?

### ISSUE THREAD

**Issue by panesofglass** [Zaid-Ajaj/Fable.Remoting#16]
I set status codes and headers in accordance with the RFCs all the time. For example, if I send back a `None`, I also often send back a `404 Not Found`. After a `POST` I typically send back a `201 Created` with a `Location` header if the result was a new resource; otherwise often a `204 No Content`. Many of our responses include cache control headers, including `ETag` or `Last-Modified`, and the subsequent Conditional GET requests need to send `If-None-Match` or `If-Modified-Since`/`If-Unmodified-Since`.

Would it be possible to expose a `Context` object of some kind in order to read/set status codes and headers?

**Comment by Nhowka** [comment]
Do you have some use case in mind?

**Comment by panesofglass** [comment]
@Nhowka I added a description with use cases above.

**Comment by Nhowka** [comment]
Do you expect to use the client alone, without the server? Because most of these uses can be encoded into the model. Here (https://github.com/Zaid-Ajaj/Fable.Remoting/pull/8#issuecomment-366115586) is an example of reading  a information that the client has sent, but I could include a more generic helper to set any header.

**Comment by Zaid-Ajaj** [comment]
@panesofglass Unfortunately, Fable.Remoting doesn't support `Context` passing between the handlers, it is possible though to read context data from the request pipeline, passing the data to the remoting handler and then inspecting the result to decide what headers to include. But honestly, if you are going that far to make it your app work in accordance with RFC, you are better off not using Fable.Remoting in the first place.

**Comment by panesofglass** [comment]
@Zaid-Ajaj thanks for the response. Would you be open to me exploring something like this? I really like how you specify the server-side interfaces and generate client, so I'd like to use this rather than creating something new yet similar.

**Comment by Nhowka** [comment]
@panesofglass I'm curious. Would something change in behaviour or only the headers would be affected?

**Comment by panesofglass** [comment]
@Nhowka I think it should only affect headers, but I need to learn more about how things work. In [gluon](http://www.tachyus.com/gluon), we use attributes and, by reflection, can inject a `Context` type that can be used to inspect and manipulate headers. I would want to try to do something similar. I think it's possible given reflection is also used when calling the handlers.

**Comment by panesofglass** [comment]
@Nhowka is the CEBasedAPI branch the future of where things are going? If so, then I'll use it. It should make it simpler to expose custom operations to work with things like status codes and headers.

**Comment by Nhowka** [comment]
@panesofglass at the moment it's just a experiment. Things were fine until I had some laziness related requirements, so most of the stuff may not even be needed in the real world. Feedback is welcome!

**Comment by panesofglass** [comment]
@Nhowka this gives me additional ideas now that I also see everything is a `POST`. :) I may make a `resource` CE after figuring out headers. It certainly looks easier to expose status code and header interactions.

**Comment by panesofglass** [comment]
After further investigation, I think the changes I wish to make go against the spirit of the project. I’ll try something separate first, then we can consider merging if similarities remain.

**Comment by Zaid-Ajaj** [comment]
> Would you be open to me exploring something like this?  

Ofcourse, as long as it the default way of *using* the library stays as simple as it is now. 

Supporting all of Http posibilities wasn't really on my todo list but it seems that many users still want the library to be fully customizable (IMHO, this misses the whole point of this library). 

@Nhowka's work on the CE based API looks really nice and makes hiding implementation details much easier, I look forward to see a working example of it.

Back implementation details :smile: so I too was thinking about `Context` from the very beginning but I didn't want to compromise the structure of the shared interface, for example if you were to introduce the idea as another parameter of the server-side functions, i.e. `Context -> 'A -> Async<'B>` it would make proxy generation harder/hacky (more than it is now) on the client. 

### Solution one: use partial application and let the remote functions have access the `Context` from provided from "outside":
```fs
// createFromContext<'t> : Context -> 't * Context
let fableWebPart = Adapter.createFromContext <| fun context -> 
  let api = {
    remoteFunc = fun arg ->  async {
      // do stuff with context
      context.statusCode <- 404
      return Error "not found"
     } 
  }

  api, context
``` 
### Solution two: use C#-style interfaces and classes where interface definitions are shared (God I need to look up how OO works in F# :sweat_smile:)
```fs
type IServer = 
    abstract member searchBooksByTitle : string -> Async<list<Book>>

// not sure if this is even correct F# syntax
type Server() as this = 
  inherit MagicalRemotingHandler
  interface IServer with 
    this.searchBooks(title: string) = 
        async {
           // do stuff with context available from MagicalRemotingHandler
           // maybe the Websharper implementation could "inspire" us to make this work
           this.Context.statusCode <- 404
           return [ ]  
        }
```  
And then you would need some more work to reflect the changes made to `Context` onto the response object before returning it back to client. Solution two has the problem that (as far as I know) the interface definitions are `[<Erase>]`ed at compile-time and will not be available at run-time like record defnitions but I need to check this first

So these were just thought, I still have no  idea how to even start on them haha

**Comment by Nhowka** [comment]
I'm working on another solution. Custom handlers of format `Context -> ResponseOverride option`. They would be called when handling the request and if they return anything, it will use the returned value instead of the default. That way the usage is kept portable and there is no need for having the context as one of the parameters.

**Comment by Zaid-Ajaj** [comment]
Usually the context provides access to both reading from the request and writing to the response, if you only have data from the request, then `RequestContext` should probably be just `Request`. I don't think you need to define your own `RequestContext`, just use the request object provided for the specific server framework as it will contain all the data the user needs for overriding the response, for example: Suave's [HttpRequest](https://github.com/SuaveIO/suave/blob/1ba57887806ba3682221afbcc65cae49f1cbad38/src/Suave/Http.fsi#L164) could be used for Fable.Remoting.Suave etc.

**Comment by Nhowka** [comment]
I wanted to do something portable, so I was extracting the data from each to a common record. Probably there's less stuff to define or override on the client. Couldn't think on anything besides headers.

**Comment by Zaid-Ajaj** [comment]
@Nhowka That makes for cleaner solution indeed. I updated some unit and integrations tests and published the changes to Nuget. I must say, I really really like the new API, clean and uniform across the packages :smile: 

I think you need to rebase your work to latest master, there shouldn't be any conflict because I only modified test projects. Sorry about that, I shouldn't be committing to master directly, I will use PR's next time I make changes :sweat_smile: 

For now I wil bel focusing on docs, samples and tests

**Comment by Nhowka** [comment]
@Zaid-Ajaj Glad you liked it! Hopefully new features won't get in the way in the vanilla usage. I'll try my best to always keep everything complex optional, so we can make everyone satisfied! 😙
