### ISSUE TITLE
How to share code and or types from other projects or libs?

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Fable.Remoting#162]
I have the following setup:

- proj Lib uses the Shared.Dose type and creates the type
- proj Server returns a Shared.Dose type in the ServerApi 

However I then get:

> The type 'Shared.Dose' does not match the type 'Shared.Dose from Lib

How can you return a shared type from a different lib? Only by just copying over?

Update: created a [repository](https://github.com/halcwb/RemotingShared) demonstrating my problem.

**Comment by Zaid-Ajaj** [comment]
Hi Casper, I don't really follow your issue 🤔 are you getting a compile error in the server-side part?

> How can you return a shared type from a different lib? Only by just copying over?

Using shared types is possible, you only have to share them between client and server and not *duplicate* them:
```
| 
| -- Shared
          | -- MyType.fs

| -- Server --> references Shared
| -- Client  --> references Shared
```
Then client and server will be able to use `Shared.MyType` both on client and server (and in the shared protocol definition)

**Comment by halcwb** [comment]
I am sorry this was a bit vague but the setup is:

| 
| -- Shared
          | -- MyType.fs
| -- Lib      --> references Shared
          | -- Creates MyType
| -- Server --> references Shared
                  --> references Lib
|         | -- Gets created MyType from Lib
| -- Client  --> references Shared

So Lib creates MyType, Server uses the create function from Lib and passes MyType on to the ServerApi remoting setup. 

Is this a bit more clear?

**Comment by Zaid-Ajaj** [comment]
The setup looks good, I don't know why you are getting this error. Is it a compile-time error? Maybe delete bin/obj folders and try build again?

**Comment by kerams** [comment]
@halcwb, when you say `references Shared/MyType.fs`, do you perhaps mean you use a file link? The fact that you do it in 2 backend projects could be the problem (`Dose` in each of the projects is a different type then).

**Comment by halcwb** [comment]
> @halcwb, when you say `references Shared/MyType.fs`, do you perhaps mean you use a file link? The fact that you do it in 2 backend projects could be the problem (`Dose` in each of the projects is a different type then).

@kerams You'r right, we are talking about file links. The shared files are meant to provide code sharing between the client and server. I think it shouldn't be a project. But I tried making Shared a project, referencing the project with the Lib and the Server, but then I run into .net version compatibility issues. The Lib project is a net46 and the Server is a netcoreapp3.1.

**Comment by kerams** [comment]
There's no other way around it. You have to reference the project (target netstandard2.0).

File referencing between client and server works because client does not run on .NET, but it's still a half-assed solution compared to sharing an entire project in my opinion. In any case, this is not an issue with Fable.Remoting.

**Comment by halcwb** [comment]
@kerams, @Zaid-Ajaj. I am not sure that this problem can be dismissed as not a Fable.Remoting issue. This goes a bit deeper than just not being able to share types from external libraries. I have tried to isolate the problem in this [repository](https://github.com/halcwb/RemotingShared). Hope this clarifies things better, or expose something stupid I did.

**Comment by Zaid-Ajaj** [comment]
Hi @halcwb, I cloned the repo and ran `fake build` and this is the error I am getting
```
ERROR in ./src/Shared.Lib/Library.fs
Module Error (from ./node_modules/fable-loader/index.js):
c:/projects/RemotingShared/src/Shared.Lib/Library.fs(15,23): (15,39) error FABLE: Cannot resolve System.IO.Path.GetTempPath
 @ ./src/Client/Client.fs 23:0-97 49:31-53 61:62-84 106:38-45 112:41-48
 @ ./src/Client/Client.fsproj
 @ multi ./src/Client/Client.fsproj ./src/Client/style.scss
```
Which makes sense because in the shared project, you can't have code that does things with `System.IO` since that is not supported in Fable. The shared project should only contain types and code that can run cross-platform (avoiding BCL as much as possible)

**Comment by Zaid-Ajaj** [comment]
After removing the `Say` module from the `Shared.Lib` project and then running `fake build` again, the project compiles and bundles like it should.

**Comment by halcwb** [comment]
@Zaid-Ajaj. Thanks for looking into this. But by removing the code from the Shared.Lib you remove my point I want to make. Suppose the Shared.Lib is just an external lib you want to make use of. Then you just can't use that external lib in the shared code, i.e. Shared.fs. And that's quite a limitation to consider. 

Suppose in the sample project, the counter record is initiated from the external lib that reads the initial value from a file. From that point on, you cannot use the counter type from the external lib in the shared code anymore. You'll have to map counter type to the shared counter type in the server project. And you can only do this by copying over from the external lib counter type to the shared counter type. I think that's the only work around. 

The other thing is that, in m.h.o the shared code should therefore be shared by file referencing, not as @kerams  said by project referencing. It therefore will be crystal clear that only the code is shared. And also, you won't be able to reference external libs, which is in that regard a good thing.

**Comment by Zaid-Ajaj** [comment]
> Suppose the Shared.Lib is just an external lib you want to make use of.

Actually, you can't just use any arbitrary library in Fable. There are strict requirements as to which subset of libraries are supported. Please check out [Compatibility with .NET](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/fable/compatibility) and [Fable Packages](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/fable/fable-packages) from The Elmish Book to understand what is supported and what isn't. 

> And you can only do this by copying over from the external lib counter type to the shared counter type. I think that's the only work around.

No, you can still use external libraries in the _server side_ to instantiate the types and map those to data transferred object types  which are in the shared project (referenced by both client and server).The server side can use any external library and you map these types like you would when transferring them from server to client as data transfer objects

**Comment by kerams** [comment]
Yes, remapping is the only option you have with types 3rd party libraries. However, this issue is not exclusive to Fable (again, nothing to do with Fable.Remoting since you could remove it and still not be able to share types in your sample repo). Imagine you wanted to use protobuf-net to serialize a type from a library you have no control over. It's not possible, you have to remap (maybe you could get it to work by manually writing a schema file for it, but that's almost the same thing as remapping).

**Comment by halcwb** [comment]
@Zaid-Ajaj and @kerams. Thanks for helping me out. I have updated my demo lab project to reflect the above discussion. This is indeed not a Fable.Remoting issue, more a caveat you need to be aware of? It caught me a bit off guard.
