### ISSUE TITLE
Problem with Nullable<>

### ISSUE THREAD

**Issue by AkosLukacs** [Zaid-Ajaj/Fable.Remoting#166]
Hi Zaid!

First I thought it's not likely that `Nullable<>` doesn't work, but looks like it's not. Found in an actual application, and later SAFE template with remoting does reproduce similar behaviour:

If there is no `Nullable<int>` in the model, everything works just fine:
![image](https://user-images.githubusercontent.com/844331/87857917-bd4d7180-c92a-11ea-8ece-ea09f85b31f8.png)

But if there is a nullable in the model, nothing happens (in the demo SAFE Template app). 
```
type Counter = { Value : int
                 NullableInt: System.Nullable<System.Int32>
                 }
```
 In my real app I got an actual exception (the value from the server was null indeed):

![image](https://user-images.githubusercontent.com/844331/87857961-0bfb0b80-c92b-11ea-8293-3860ecb63afd.png)

The server does send the expected value with Nullable:
![image](https://user-images.githubusercontent.com/844331/87858000-4e244d00-c92b-11ea-86c7-6a11d892f1b0.png)

Version:
`6.3.1` in my real application
`5.11` or `6.3.1` in the SAFE template

Repro repo is here: https://github.com/AkosLukacs/fable.remoting.nullable

**Comment by AkosLukacs** [comment]
Small update with the new binary serialization:

**JSON** serialization: doesn't work if either the server sends null or a number
**Binary** serialization: 
 - does work if the server sends null
 - doesn't work if the server sends an actual number

**Comment by kerams** [comment]
Yeah, I've overlooked `Nullable`. Will try to fix it in #165.

**Comment by Zaid-Ajaj** [comment]
Hi @AkosLukacs, 

It looks like we overlooked `Nullable<'t>` indeed because no one uses it. I was adding support for it in SimpleJson but it seems that it is not even supported in Fable 😱 using `{Nullable}.Value` and `{Nullable}.HasValue` gives me compile errors with latest Fable (2.10.1)
```
C:/projects/simplejson/test/Tests.fs(492,25): (492,56) error FABLE: Cannot resolve System.Nullable`1.get_HasValue
C:/projects/simplejson/test/Tests.fs(493,20): (493,52) error FABLE: Cannot resolve System.Nullable`1.get_HasValue
C:/projects/simplejson/test/Tests.fs(494,24): (494,53) error FABLE: Cannot resolve System.Nullable`1.get_Value
```

**Comment by Zaid-Ajaj** [comment]
I filed an issue on Fable's repo [Support for System.Nullable<'t>](https://github.com/fable-compiler/Fable/issues/2121) so will wait until Fable actually supports it so that I could test my implementation fix :smile:

**Comment by AkosLukacs** [comment]
Thank you for the super quick response!
Well, yes, this is what happens when the serialization "just works", and EF types creep into the client 😨 
Time for some organization on my side I guess...
