### ISSUE TITLE
Sending mutiple arguments fails when the client function is partially applied

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#17]
Related https://github.com/fable-elmish/elmish/issues/142

**Comment by Nhowka** [comment]
I have a [fix on my branch](https://github.com/Nhowka/Fable.Remoting/blob/CEBasedAPI/Fable.Remoting.Client/Proxy.fs#L181-L218) with the API changes. It's ready to merge and should be easy to migrate. I tried not to break existing code but I'm not sure if I succeeded.

Also it should make it easier to support other servers as the parsing part is shared but the actual request handling is made inside the specific plugin. The only problem is that it requires open both `Fable.Remoting.Server` and `Fable.Remoting.<specific>` to override the computation expression implementation.

**Comment by Zaid-Ajaj** [comment]
First of all, if you think it is ready to merge, just merge it, you have write-access too on this repo as a collaborator :smile:. I will test it again my self locally anyways but you can also simply run the integration tests for Suave or Giraffe
```bash
cd Fable.Remoting.IntegrationTests
cd Server.Suave # or Server.Giraffe
# run server
dotnet run 
# in another tab, run the client
cd ..
cd Client
dotnet fable npm-run start
# server runs on http://localhost:8080
# client runs on http://localhost:8081
# navigate to the client to the see the results of the Qunit tests
```
Btw, we need more (integration) tests for Saturn as well and many many unit tests for multi-arg remote functions
