### ISSUE TITLE
Can be used with React Native?

### ISSUE THREAD

**Issue by fremontmj** [Zaid-Ajaj/Fable.Remoting#179]
Hi,

I’m looking into using Fable to build a React Native app, and I’m hoping to use Fable.Remoting. Is that combination supported?

Thanks much!

**Comment by Zaid-Ajaj** [comment]
Hi there @fremontmj, 
According to React Native docs, it is possible to use XMLHttpRequest directly which means that Fable.Remoting.Client should work as expected when used from React Native, give it a try and let us know if you encounter any issues ;)

**Comment by fremontmj** [comment]
That’s great news. Silly me, I didn’t think to look in the React Native docs, only Fable.

@Zaid-Ajaj, between writing Feliz (very cool), Fable.Remoting (very cool), and The Elmish Book (masterful), when do you have time to sleep?

Best,

Mike

**Comment by Zaid-Ajaj** [comment]
Thanks a lot Mike :heart: really appreciate it and no worries! I do take a time off from these projects every now and then :smile:
