### ISSUE TITLE
Add proper documentation site

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#18]
document everything

**Comment by Nhowka** [comment]
What if we use the wiki from GitHub? Could be easier to maintain.

**Comment by Zaid-Ajaj** [comment]
I was actually thinking of using the awesomeness of [Gitbook](https://github.com/Zaid-Ajaj/gitbook-template) :smile:

**Comment by Zaid-Ajaj** [comment]
Fixed: https://zaid-ajaj.github.io/Fable.Remoting/

**Comment by StachuDotNet** [comment]
Super awesome! Great job :)
