### ISSUE TITLE
Implement Remoting.Client utilities for file upload and download

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#185]
Basically a couple of (extention) functions on the client side of things:
 - `(instance: File).readAsByteArray() : byte[]` so that a `File` coming from `Html.input` can be easily turned into binary content that can be sent to the server (upload)
 - ` (instance: byte[]).download(filename: string) -> unit` for file download once someone has hold of some `byte[]` returned from the backend, we might need to infer the content type based on the extension of the file.
 - docs for uploading and downloading files because recently many people have been asking for this

> `readAsByteArray()` might return `Async<byte[]>` (not sure) but that should be no problem, really

**Comment by Zaid-Ajaj** [comment]
Docs here https://zaid-ajaj.github.io/Fable.Remoting/src/upload-and-download.html

**Comment by kaashyapan** [comment]
Is it possible to monitor file upload/download progress with the remoting client utility ?

**Comment by Zaid-Ajaj** [comment]
@kaashyapan Not really with the way the client proxy works
