### ISSUE TITLE
Fable.Remoting.MsgPack compilation error after upgrading to Fable 3.0.0-nagareyama-alpha-015

### ISSUE THREAD

**Issue by bklop** [Zaid-Ajaj/Fable.Remoting#190]
I have an Elmish/Fable.Remoting/Feliz application that I tried upgrading to 3.0.0-nagareyama-alpha-015. I'm also using the latest Fable.Remoting.

The Fable compiler fails when trying to compile the following file:
.fable/Fable.Remoting.MsgPack.1.6.0/Write.fs(10,13): (10,17) error FSHARP: The namespace 'Linq' is not defined. (code 39)

MsgPack.Write is not used by the Fable.Remoting client, correct?
Note that I do not reference Fable.Remoting.MsgPack in my client, I only have a reference to Fable.Remoting.Client.

I'm not entirely sure that this is a Fable.Remoting issue, but I thought I'd check here first.

**Comment by kerams** [comment]
I think I've seen this reported somewhere. You're right that Remoting itself does not call the Write module at all.

Try moving `open System.Linq.Expressions` (and probably the 2 TypeShape usings as well) below the `#if` on line 15 in `.fable/Fable.Remoting.MsgPack.1.6.0/Write.fs`. If that compiles, we can do the same thing in the repo (feel free to open a PR too).

**Comment by bklop** [comment]
Thanks, that fixed the issue!
