### ISSUE TITLE
Generated Docs do not display DateTime

### ISSUE THREAD

**Issue by Freymaurer** [Zaid-Ajaj/Fable.Remoting#197]
Hello, i am currently adding descriptions and examples to a SAFE stack via Fable.Remoting and i noticed that any function with DateTime will not show up in the examples. In the following i'll show my most minimal example of this behavior.

```fsharp
type IAnnotatorAPIv1 = {
    getTestString : System.DateTime -> Async<string>
}
```

```fsharp
let annotatorApi = {
    getTestString = fun strOpt -> async { return sprintf "Test string: %A" strOpt 
}
```

```fsharp
annotatorDocsv1.route <@ fun api -> api.getTestString @>
        |> annotatorDocsv1.alias "Get Test String (<code>getTestString</code>)"
        |> annotatorDocsv1.description "test description"
        |> annotatorDocsv1.example <@ fun api -> api.getTestString (System.DateTime(2020,11,17)) @>
```

![grafik](https://user-images.githubusercontent.com/39732517/99670272-92a62d80-2a70-11eb-9b62-6df7d51fad02.png)

**Comment by Zaid-Ajaj** [comment]
Hi there @Freymaurer, thanks a lot for reporting the issue, I will have a look at it soon! 

I am not sure whether this is just for demo purposes but you probably shouldn't use `DateTime` in the context of a web application because it doesn't account the offset of the timezone of the server vs. the timezone of the client which can give you problems that are not fun to work with at all. Use `DateTimeOffset` instead in combination with NodaTime if doing any time arithmetic

**Comment by Freymaurer** [comment]
Hi thanks for the quick response! This was just for demo purposes. The 'DateTime' we want to pass to the server was previously requested from the server and is part of a search query.

**Comment by Zaid-Ajaj** [comment]
@Freymaurer I can confirm that the docs feature is broken in latest versions. It doesn't have to do with `DateTime` per se, the examples, alias and other values aren't coming through the API for some reason. I will investigate and keep you posted

**Comment by Zaid-Ajaj** [comment]
Fixed as of latest `Fable.Remoting.Giraffe` and other server-side packages 🚀 let me know if you encounter any more of these issues :smile:

**Comment by Freymaurer** [comment]
@Zaid-Ajaj Ok i updated Fable.Remoting.Giraffe to 4.13 from my previous version 4.10. I am using it in a SAFE.template of version 1.22.4 and i get a 404 error to all Fable.Remoting related apis. Did i forget to update a dependency?

**Comment by Zaid-Ajaj** [comment]
> I am using it in a SAFE.template of version 1.22.4 and i get a 404 error to all Fable.Remoting related apis. Did i forget to update a dependency?

Hmm, that's weird 🤔 are you getting 404 in production or development? You _might_ need to update Giraffe or Saturn but I am not sure because it could be an issue with #187 that is implemented in v4.11 of Fable.Remoting.Giraffe

Can you please share the bit of the code where you are exposing the remoting `HttpHandler`? cc @Arshia001 might know something too

**Comment by Freymaurer** [comment]
The issue appeared in this rather big project (https://github.com/nfdi4plants/Swate). I am not sure when i will get to do a minimal repo to reproduce this.

**Comment by Zaid-Ajaj** [comment]
You can also enable the diagnostics logger (see [Troubleshooting](https://zaid-ajaj.github.io/Fable.Remoting/src/troubleshoot.html)) to see which routes are generated and then compare those routes with what the browser sends

**Comment by Zaid-Ajaj** [comment]
@Freymaurer I see this part
```fs
let mainApiController = router {
    forward @"/IAnnotatorAPI" (fun next ctx ->
        // check if the version in the path exists for the api
        let cString = 
            // user secret part for production
            let settings = ctx.GetService<IConfiguration>()
            settings.["Swate:ConnectionString"]
        createIAnnotatorApiWithVersion cString next ctx
    )
    forward @"/ITestAPI" (fun next ctx ->
        // check if the version in the path exists for the api
        testWebApp next ctx
    )
}
```
Can you try removing the `@` from the route definition?

**Comment by Zaid-Ajaj** [comment]
@Freymaurer Please open another issue if the problem persists to track and fix it from there
