### ISSUE TITLE
Support  netstandard2.0

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.Remoting#2]
Would it be possible to support netstandard2.0 ?

Seems like it' support netcore2.0, but I don't what this version is for.

**Comment by MangelMaxime** [comment]
Hum before investigating this issue I think I understand my mistake.

**Comment by Zaid-Ajaj** [comment]
Hello @MangelMaxime, sorry didn't have time to update the README.md yet. The library is now actually Work in progress and I am porting everything to netcore2.0 and testing it as well, but I was blocked at [this issue](https://github.com/dotnet/corefx/issues/23387). So I am waiting for it to be merged and then I can continue

**Comment by MangelMaxime** [comment]
Hello @Zaid-Ajaj no problem, I had another problem in my project which prevent me to use Fable.Remoting for now. (Nothing to due with Fable.Remoting itself^^).

One, day I will be able to work with it :D or perhaps add support for another backend when I have the time.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime I look forward to it :smile:

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime After countless tries, I finally found a workaround for fixing reflection code and Fable.Remoting is up and running on netstandard2.0 for Suave :tada: :tada: :tada: (so happy!)

I made sure all tests pass and added an integration tests project.

I just published latest versions Nuget (probably not indexed yet):
- Fable.Remoting.Suave 1.2.1 
- Fable.Remoting.Client 1.2.0 

Please play around with it if you are still interested and let me know if you face any problems :smile:

**Comment by MangelMaxime** [comment]
Awesome :) 👏 

If i have again a project which can use it, I will not miss to try it :)
