### ISSUE TITLE
Add Fable.Remoting.Nancy

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#20]
Will investigate this myself, dependency injection becomes straight-forward, just like [Cable](https://github.com/Zaid-Ajaj/Cable)

**Comment by Nhowka** [comment]
Have you got into it? I am not sure that the abstract class from the server is generic enough for future versions... 🤔

**Comment by Zaid-Ajaj** [comment]
Not yet, but I am considering to exclude Nancy from the list for now, becuase it is really a C# library, I think supporting just OWIN should be enough. Don't worry about the abstract class, if need be, a specialized version for Nancy or other should do it :wink:

**Comment by Zaid-Ajaj** [comment]
Fixed in #58 -> Use Aspnet core adapter
