### ISSUE TITLE
Update TypeShape 8.0.1 -> 9.0.0

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#226]
Some weird _FATAL_ runtime error occurs with TypeShape and it happens only on deployed application in azure (assuming it is running net5.0) but works locally just fine using either -c Debug or -c Release

```
Fatal error. Internal CLR error. (0x80131506) at System.RuntimeType.get_IsByRefLike() at TypeShape.Core.Core+TypeShapeImpl.resolveTypeShape(System.Type) at TypeShape.Core.Core+ShapeFSharpRecord`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor() at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean) at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo) at TypeShape.Core.Core+TypeShapeImpl.activateGeneric(System.Type, System.Type[], System.Object[]) at TypeShape.Core.Core.Activator.CreateInstanceGeneric.Static[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpOption`1<System.Type[]>, Microsoft.FSharp.Core.FSharpOption`1<System.Object[]>) at TypeShape.Core.Core+Shape.|FSharpRecord|_|(TypeShape) at Fable.Remoting.Server.Proxy.makeApiProxy[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Fable.Remoting.Server.RemotingOptions`2<System.__Canon,System.__Canon>) at Fable.Remoting.Giraffe.GiraffeUtil.buildFromImplementation[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.AspNetCore.Http.HttpContext,System.__Canon>, Fable.Remoting.Server.RemotingOptions`2<Microsoft.AspNetCore.Http.HttpContext,System.__Canon>) at Fable.Remoting.Giraffe.Remoting.buildHttpHandler[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Fable.Remoting.Server.RemotingOptions`2<Microsoft.AspNetCore.Http.HttpContext,System.__Canon>) at <StartupCode$Server>.$Server.main@()
```
So I am thinking it might have to do with TypeShape using an old reflection API so I think we should update it to latest 9.0.0 just in case. What do you think, @kerams?

**Comment by kerams** [comment]
That is really weird. Updating is certainly worth a shot, it won't hurt anything. However, TypeShape isn't pinned to a major version, are you sure you're not already deploying your application with v9?

**Comment by Zaid-Ajaj** [comment]
You are right @kerams it [looks like it](https://github.com/SAFE-Stack/SAFE-template/blob/5d486156a429819b3804518e57b1b69a4b31e7e5/Content/default/paket.lock#L384) this is just paket lock from the SAFE template. Maybe that's the problem

**Comment by kerams** [comment]
https://github.com/eiriktsarpalis/TypeShape/commit/a8be8c77f0719e557b3c7ead2a62b8b23f80758b#diff-6a7780a357a197c700a5c9acdacd22efa6ea59e35cfb542b4ad370acf8766565R147-R151
This has been added in v9 and according to the call stack you're hitting the `#else` branch for some reason. Maybe ask Eirik if he has any idea what's up?

In the meantime, I'm sure locking into v8 will help you.

**Comment by Zaid-Ajaj** [comment]
Yeah I was talking to @isaacabraham about it (he reported the issue) and I think we should either update TypeShape to 9.0.0 or set better version constraints to say TypeShape should be >= 8.0.1 && < 9.0.0

**Comment by eiriktsarpalis** [comment]
@Zaid-Ajaj could you share the full stacktrace?

**Comment by eiriktsarpalis** [comment]
Are you consuming TypeShape using the nuget package or by embedding its source file? The former only targets netstandard2.0 which uses the workaround referenced in https://github.com/eiriktsarpalis/TypeShape/commit/a8be8c77f0719e557b3c7ead2a62b8b23f80758b#diff-6a7780a357a197c700a5c9acdacd22efa6ea59e35cfb542b4ad370acf8766565R147-R151

**Comment by Zaid-Ajaj** [comment]
@eiriktsarpalis The stack trace was posted in [TypeShape/#45](https://github.com/eiriktsarpalis/TypeShape/issues/45). Do you recommend to use the source file or the nuget package v9?
