### ISSUE TITLE
Fable.Remoting.Json 2.0.0 is not released

### ISSUE THREAD

**Issue by theimowski** [Zaid-Ajaj/Fable.Remoting#23]
I tried to add `Fable.Remoting.Giraffe` 2.0 to SAFE-template, but the dependency on `Fable.Remoting.Json 2.0` is unsatisfied:

```
Paket failed with
-> There was a version conflict during package resolution.
     Resolved packages:
      - Fable.Remoting.Giraffe 2.0.0
      - FSharp.Core 4.3.4
      - Microsoft.DotNet.Watcher.Tools 1.0.0
      - Saturn 0.4.3
     Conflict detected:
      - Fable.Remoting.Giraffe 2.0.0 requested package Fable.Remoting.Json: >= 2.0
      - Available versions:
        - (1.3, [https://api.nuget.org/v3/index.json])
        - (1.3.0, [https://api.nuget.org/v3/index.json])
        - (1.2.0, [https://api.nuget.org/v3/index.json])
        - (1.1.0, [https://api.nuget.org/v3/index.json])
        - (1.0.0, [https://api.nuget.org/v3/index.json])
```

**Comment by Zaid-Ajaj** [comment]
Hmm it looks like the Json package was bumped to version 2.0 along the previous commits :sweat_smile: I published it now, should be available in a couple of hours when Nuget indexes it

**Comment by Nhowka** [comment]
Sorry about that! 😅
As the client and server couldn't talk with mismatching versions, I ended upgrading everything even what was not needed.

**Comment by theimowski** [comment]
Hmm now the same story is with `Fable.Remoting.Reflection` :

```
Conflict detected:
   - Fable.Remoting.Server 2.0.0 requested package Fable.Remoting.Reflection: >= 3.0
   - Available versions:
     - (2.1, [https://api.nuget.org/v3/index.json])
     - (2.1.0, [https://api.nuget.org/v3/index.json])
     - (2.0.0, [https://api.nuget.org/v3/index.json])
     - (1.0.0, [https://api.nuget.org/v3/index.json])
```

**Comment by Zaid-Ajaj** [comment]
Bumped `Fable.Remoting.Reflection` to 3.0 and published it, everything should now work fine (when nuget finishes indexing). @theimowski Thank you for reporting these issues! I guess I will a couple of test projects that use the Nuget packages to avoid such problems in the future
