### ISSUE TITLE
MsgPack invalid casting

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Fable.Remoting#235]
I'm encountering an exception when initializing the .NET MsgPack serializer. I tried finding where this casting is happening, but no luck. The exception on my end is happening [here](https://github.com/Shmew/Fable.SignalR/blob/master/src/Fable.SignalR.Shared/MsgPack.fs#L32). I'm having trouble properly reproducing the exception as it isn't happening in my actual repo (I tried both updating and downgrading packages with no luck), but is for [others](https://github.com/Shmew/Fable.SignalR/issues/21). SignalR swallows the exception normally so the reproduction he linked won't reveal it, I had to reference the `Fable.SignalR` projects directly and run the debugger to find this:

![image](https://user-images.githubusercontent.com/11186595/113061065-1b4b7d80-9177-11eb-9976-059f7c73c798.png)

If I can do anything else to help please let me know.

**Comment by kerams** [comment]
Do Details contain the call stack?

**Comment by Shmew** [comment]
> Do Details contain the call stack?

![image](https://user-images.githubusercontent.com/11186595/113178208-f9ec9f00-9213-11eb-9381-aaeea3989969.png)

![image](https://user-images.githubusercontent.com/11186595/113178049-cc9ff100-9213-11eb-98f1-67d016cf0c7d.png)

**Comment by Shmew** [comment]
As we discussed in the issue on my repo, we have this resolved. @kerams do you want me to leave this open until there's a better error message? If not feel free to close the issue.

Thanks!
