### ISSUE TITLE
Fable.Remoting and kubernetes results in 404

### ISSUE THREAD

**Issue by runefs** [Zaid-Ajaj/Fable.Remoting#253]
I have a docker container with the Giraffe example running inside it. The container is deployed in a kubernetes pod. If I request it from another pod in the cluster or if I forward the container port to localhost and request it I get Api 404. However if I run the same application locally it works as expected

**Comment by Zaid-Ajaj** [comment]
Hi there @runefs, I am not familiar with kubernetes so I am not sure how to debug this. Can you please confirm that this indeed a Fable.Remoting issue? For example, if you have a normal Giraffe route next to the handler of remoting, can you still reach it?

**Comment by runefs** [comment]
Of that I am positive. I stubbled upon this in the process of rewriting a REST API to use Fable.Remoting instead. Could it have something to do with the bind address being different than the requested? Ie the bund address is 0,0,0,0:8085 but is accessed through http://kubernetes-service-name:8085. This does work for giraffe in general

**Comment by Zaid-Ajaj** [comment]
> This does work for giraffe in general

Fable.Remoting creates Giraffe handlers so I would assume it works here too. 

That said, if you could provide a sample to reproduce the problem, that would be great! I can try to spin up local kubernetes thingy and see what going on. (never that before though, so that might take a bit)

**Comment by runefs** [comment]
It took me forever to recreate a small sample to reproduce the problem. There was however a straightforward reason for why it took so long. There's no issue. I had inadvertently changed the binding address from 0.0.0.0 to localhost (copy-paste of example code I guess). binding to localhost doesn't work in a container. However, when I tried to run it locally it did of course work and I must have tested the regular REST API before making that change
