### ISSUE TITLE
Error in BinarySerialization

### ISSUE THREAD

**Issue by tforkmann** [Zaid-Ajaj/Fable.Remoting#257]
Hi there,

i get following issue with the BinarySerialization:

exn Error: Position 441, byte 201, expected type Byte.

The error is probably coming from this patter match.

https://github.com/Zaid-Ajaj/Fable.Remoting/blob/f04255c7cb8c8c3316d1730c12c1a570975281cb/Fable.Remoting.MsgPack/Read.fs#L441

Any idea how to fix that?

When I get rid of BinarySerialization Fable.Remoting works well.

Thanks in advance!

**Comment by kerams** [comment]
I'd have to see the response type you're trying to serialize. Also make sure your client _and_ server are using the same Fable.Remoting.MsgPack version.

**Comment by tforkmann** [comment]
Both client and server using Fable.Remoting.MsgPack 1.12
I reduced the qty of rows. Please find the msg attached.
The error appears looks like this now:
exn Error: Position 753, byte 201, expected type Byte.

Here response type:

```fsharp

type SAPId =
    | SAPId of SAPId: int

type MeterDataRow =
    { SAPId: Ids.SAPId
      AggregateTypeId: byte
      AggregateType: string
      ParameterId: byte
      Parameter: string
      LocationId: Ids.LocationId
      Standort: string
      Datum: DateTime
      Wert: float
      Anlage: string
      Description: string
      Unit: string }

type TechnicalParametersRow =
    { Date: DateTime
      MeterDataRow: MeterDataRow [] }

type TechnicalParameters =
    { Standort: string
      Anlage: string
      MeterDesc: (Ids.SAPId * string) []
      Rows: TechnicalParametersRow [] }
```

The msg is quite big. 
[msg.txt](https://github.com/Zaid-Ajaj/Fable.Remoting/files/6646725/msg.txt)

**Comment by kerams** [comment]
Thanks, found the problem. Fix incoming.

**Comment by tforkmann** [comment]
Awesome!! Works
