### ISSUE TITLE
How to specify a particular named httpclient to use with the dotnetclient

### ISSUE THREAD

**Issue by runefs** [Zaid-Ajaj/Fable.Remoting#296]
Most of our HTTP calls have a Polly policy attached to them. They are all configured as named HTTP clients however I can't see any way to specify to the client to use such an HTTP client. Is it possible to specify a named HTTP client to be used for a given client?

**Comment by runefs** [comment]
After investigating the code I found that it is indeed possible to provider a specific HttpClient `Http. withHttpClient` would be the method. So it would seem that it was merely a documentation issue.(Whether that was me not being able to find it in the documentation or the feature not being documented I don't know)

**Comment by Zaid-Ajaj** [comment]
Hi there @runefs sorry about the late reply! This was indeed a docs issue and I have now updated the docs and included a section about using your own HttpClient in the proxy definition

https://zaid-ajaj.github.io/Fable.Remoting/#/client-setup/dotnet#provide-an-existing-httpclient-to-make-the-requests
