### ISSUE TITLE
Similar alternatives to FABLE

### ISSUE THREAD

**Issue by AntonioL** [Zaid-Ajaj/Fable.Remoting#299]
This is not an issue.

I am doing some research, do you recall any similar alternatives in other languages which allow you to define type-safe servers and client implementations? Did you come across this pattern elsewhere?

**Comment by Zaid-Ajaj** [comment]
Hi there Antonio 👋 

This project was inspired by [WebSharper](https://websharper.com/) and it's [Remoting](https://developers.websharper.com/docs/v4.x/fs/remoting) feature. As of latest web sharper version, it supports both C# and F#

ScalaJS has [autowire](https://github.com/lihaoyi/autowire) with similar goals

TypeScript has a bunch of these RPC implementation such as [this one](https://github.com/vasyas/typescript-rest-rpc)

The pattern is pretty common for languages that support full stack compilation and usually the language should support runtime reflection but even without it, a limited set of features can still be implemented.

Hope this helps 🙏
