### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Fable.Remoting#3]
Please.

**Comment by pkese** [comment]
I did, thanks.

In the end I used almost out-of-the box https://github.com/ncthbrt/Fable.Websockets.Elmish implementation on client and somewhat modified one on the server. On server I've replaced their proposed state machine with a classic Elmish, so that I can use the same stack (and mindset) on both client and server.

I'm nevertheless looking forward to - if you ever manage to create your own implementation.
It's just that your code feels very well thought of and polished.

**Comment by Zaid-Ajaj** [comment]
Thanks for the kind words! I will keep this issue open and will let you know if I make progress on the feature :smile:

**Comment by Zaid-Ajaj** [comment]
Closing because @Nhowka already doing awesome work on [Elmish.Remoting](https://github.com/Nhowka/Elmish.Remoting) that solves the websocket remoting channels

**Comment by srid** [comment]
What's the relation between `Elmish.Bridge` and `Fable.Remoting`? Are they exclusive from one another? Or can the latter use the former to provide websocket transport?

**Comment by pkese** [comment]
@srid They are mostly orthogonal. You can use one or the other or both.

If you have an asynchronous Elmish app on server and if it needs to communicate state back to client, then Elmish.Bridge is worth considering.  
And it fits really nicely into Elmish architecture.

**Comment by kerams** [comment]
Nowadays there's also https://github.com/Shmew/Fable.SignalR, but SignalR is much fatter than some simple WebSocket communication layer.
