### ISSUE TITLE
Binary serialization bug with Result.Error

### ISSUE THREAD

**Issue by sWW26** [Zaid-Ajaj/Fable.Remoting#304]
I'm getting some weird behaviour when using binary serialization with the `Result` type when the `Error` contains a string.

I've had a brief poke around to see if I can repro it using only the `Fable.Remoting.MsgPack` library directly however that seems to work fine.  It only seems to happen when going through the proxy / Giraffe?

I've put together a little sample app here that shows the issue: https://github.com/sWW26/FableBinarySerializationBug

The API always returns `Error "Test"` however the string ends up getting mangled.
![image](https://user-images.githubusercontent.com/6764717/177636003-a27cebcd-625a-4ad9-8065-574562bdaebf.png)

**Comment by kerams** [comment]
Will take a look.

**Comment by kerams** [comment]
Very strange - the first 2 responses contain corrupted (?) data. From the 3rd onwards, everything seems to be OK. Doesn't ring any bells, so I'll have to sleep on this.

**Comment by kerams** [comment]
@sWW26, I've managed to ascertain this issue is deeper than Remoting. Could be due to JIT, but F# codegen is more likely. Follow the progress here https://github.com/dotnet/fsharp/issues/13447.

**Comment by sWW26** [comment]
Thanks for investigating!

**Comment by Zaid-Ajaj** [comment]
Closing as fixed since latest Fable.Remoting.MsgPack v1.18.0
