### ISSUE TITLE
[Question] Is there a particular reason why Fable.Remoting.AzureFunctions.Worker is locked to FSharp.Core < 6.0.0

### ISSUE THREAD

**Issue by DieselMeister** [Zaid-Ajaj/Fable.Remoting#311]
Is there a particular reason why Fable.Remoting.AzureFunctions.Worker is locked to FSharp.Core < 6.0.0

**Comment by Zaid-Ajaj** [comment]
not really, it should be >= 4.7.2 I'll fix it, thanks for letting me know!

**Comment by DieselMeister** [comment]
Thanks :)

**Comment by Zaid-Ajaj** [comment]
Done 😄

**Comment by DieselMeister** [comment]
Wait.. Already? Don't you get some sleep?

Thank you!

**Comment by Zaid-Ajaj** [comment]
> Wait.. Already? Don't you need some sleep?

Priorities 😬 

> Thank you!

You are welcome! I hope I published the right package now. Feel free to re-open the issue if I haven't 😄
