### ISSUE TITLE
[minor] Update to Fable.SimpleJson v3.24 to get the CSP compliant fix

### ISSUE THREAD

**Issue by cr3wdayt5p** [Zaid-Ajaj/Fable.Remoting#327]
Fable.SimpleJson v3.24 allows for using a stricter 'content-security-policy' header (no 'unsafe-eval' needed).

**Comment by Zaid-Ajaj** [comment]
Fixed as of Fable.Remoting.Client v7.24 which includes Fable.SimpleJson v3.24
