### ISSUE TITLE
js uses not defined value

### ISSUE THREAD

**Issue by hesxenon** [Zaid-Ajaj/Fable.Remoting#329]
Hi, I'm just trying to get started with Fable (coming from JS) in general and thought Fable.Remoting looked really nice.

However it seems that following the "from scratch" guide for suave produces broken JS and I don't know why.

<details>
  <summary>.fsproj</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../contracts/Contracts.fs" />
    <Compile Include="Server.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.7" />
    <PackageReference Include="Fable.Core" Version="3.7.1" />
    <PackageReference Include="Fable.Remoting.Suave" Version="4.32.0" />
  </ItemGroup>

</Project>
```
</details>

<details>
  <summary>Server.fs</summary>

```fsharp
module Server

open Suave
open Suave.Filters
open Suave.Successful
open Fable.Remoting.Server
open Fable.Remoting.Suave

let todoStore: Contracts.todoStore = { test = async { return "Hello World" } }

let api: WebPart =
  Remoting.createApi () |> Remoting.fromValue todoStore |> Remoting.buildWebPart

startWebServer defaultConfig api
```
</details>

<details>
  <summary>Server.fs.js</summary>

```javascript
import { singleton } from "./fable_modules/fable-library.3.7.20/AsyncBuilder.js";
import { todoStore as todoStore_1 } from "../contracts/Contracts.fs.js";

export const todoStore = new todoStore_1(singleton.Delay(() => singleton.Return("Hello World")));

export const api = Fable_Remoting_Suave_Remoting_buildWebPart(Fable_Remoting_Server_Remoting_fromValue(todoStore, Fable_Remoting_Server_Remoting_createApi()));

Suave_Web_startWebServer(Suave_Web_defaultConfig, api);

//# sourceMappingURL=Server.fs.js.map
```
</details>

`Fable_Remoting_Suave_Remoting_buildWebPart` obviously doesn't exist in the scope where it's used. Any ideas why and what I did wrong?

**Comment by kerams** [comment]
Suave is the web server - it runs on .NET and you should not compile it with Fable.

**Comment by hesxenon** [comment]
well, that explains it then. So if suave is strictly .net and Fable is a F#
to JS transpiler, what exactly is Fable.Remoting.Suave? An opinionated way
on how to work with suave? And why is it in the Fable namespace if it's not
supposed to interact with fable?

**Comment by kerams** [comment]
Fable.Remoting.Client package is what you use in the client project which you compile with Fable. Fable.Remoting.(Suave | Giraffe | etc.) on the other hand are purely .NET packages, which are to be used in the corresponding web server, so that it knows how to handle the Remoting RPC traffic. Both sides are needed - it does not make sense to use one without the other. Fable.Remoting is the name of this project and therefore it is also the main namespace for all Nuget packages, even though most of them aren't technically Fable-compatible.
