### ISSUE TITLE
Does fable remoting do runtime validation?

### ISSUE THREAD

**Issue by Darkle** [Zaid-Ajaj/Fable.Remoting#331]
Hi, I'm brand new to using Fable.Remoting and was wondering if Fable.Remoting does any runtime validation. 

For instance, what if a client is misconfigured (or malicous) and sending bad data? Would Fable.Remoting throw an error on the server or would it let the bad data through?

**Comment by Zaid-Ajaj** [comment]
Hi there @Darkle, remoting does not do any special validation to the data and assume the client is in sync with the server. There are patterns you can use where you implement parsing validation for your domain types in the shared project and use the validation logic both on the frontend and backend.

**Comment by Darkle** [comment]
Ok, thanks.
