### ISSUE TITLE
expected error structure

### ISSUE THREAD

**Issue by hesxenon** [Zaid-Ajaj/Fable.Remoting#338]
hey, sorry to open an issue for this, could you point to where the client handles error responses? Specifically which structure is expected? 

Currently I'm sending `{status: int; body: string}` but that doesn't seem to be correct?

**Comment by Zaid-Ajaj** [comment]
The error returned from a Remoting backend is determined by the defined `errorHandler` see [Error handling](https://zaid-ajaj.github.io/Fable.Remoting/#/advanced/error-handling)

> Currently I'm sending {status: int; body: string} but that doesn't seem to be correct?

It's not about the shape, it's about the `StatusCode` in the response _header_, not the body. 

In general however, any non-200 status code is an error on the client that results in `ProxyRequestException`. See how the client [handles it](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Client/Proxy.fs#L164)

**Comment by hesxenon** [comment]
yeah, I had found that point in the client but I don't get what kind of body is expected.

Im asking because somewhere my response is translated into this error "Cannot convert {"text":"test"} to ["Array",null]"

**Comment by hesxenon** [comment]
... I overwrote the statuscode by accident. Thx for your help :)
