### ISSUE TITLE
Make HttpContext available from ErrorHandler

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#34]
Instead of 
```
Exception -> RouteInfo -> ErrorResult
```
I think it would be much nicer to have 
```
Exception -> HttpContext -> ErrorResult
```
There are many reasons why more context information is needed, for example, the `ErrorHandler` is where most people put their logging logic when things go wrong. When that happens, being able to trace back the request using the context is extremely convenient.

@Nhowka What do you think?

Related:
 - [Suave.SerilogExtensions](https://github.com/Zaid-Ajaj/Suave.SerilogExtensions) easy logging integration with Fable.Remoting.Suave

**Comment by Nhowka** [comment]
I was using the Serilog extension when investigating the async bug. I think that is a great idea, but it would be a breaking change code-wise. Are we ready for it? 😋

**Comment by Zaid-Ajaj** [comment]
We could add the `HttpContext` as a field to `RouteInfo` then we won't be breaking anything, so that's another option

**Comment by Nhowka** [comment]
Perfect! That way it's safe and nobody will be sad! 😙
