### ISSUE TITLE
[Feature Request] Namespaced endpoints

### ISSUE THREAD

**Issue by Darkle** [Zaid-Ajaj/Fable.Remoting#341]
Hi, I think it would be super handy if it were possible to namespace endpoints, so that when using the client you could do something like this:

```fsharp
server.users.getUser id
server.users.addUser {|name="Foo"; id=2|}
server.posts.getPost id
```

**Comment by Zaid-Ajaj** [comment]
Hi there @Darkle, what you are asking for today is currently possible if you create multiple server protocols:
```fs
users.getUser 42
posts.getPost 1
```
where `users` and `posts` are two different protocols. 

Although technically possible, adding namespacing to protocols would mean to nest the records inside other records. I feel like this overcomplicates the implementation and would require a different way to customize the routes. Using multiple protocols is the recommended way ✅

**Comment by Darkle** [comment]
Do you mean something like this?
```fs
let routeBuilder (typeName: string) (methodName: string) =
  sprintf "/api/%s/%s" typeName methodName

let posts =
  Remoting.createApi ("http://localhost:3002")
  |> Remoting.withRouteBuilder routeBuilder
  |> Remoting.buildProxy<PostsEndpoints>

let users =
  Remoting.createApi ("http://localhost:3002")
  |> Remoting.withRouteBuilder routeBuilder
  |> Remoting.buildProxy<UsersEndpoints>
```

**Comment by Zaid-Ajaj** [comment]
Yes, exactly like that!

**Comment by Darkle** [comment]
Thanks.
