### ISSUE TITLE
Fable.Remoting.Client is incompatible with FSharp.Core on Fable 4

### ISSUE THREAD

**Issue by brianberns** [Zaid-Ajaj/Fable.Remoting#350]
Attempting to upgrade a test app from Fable 3 to Fable 4 produces the following error:

    Parsing src\App.fsproj...
    src> cmd /C dotnet restore App.csproj -p:FABLE_COMPILER=true -p:FABLE_COMPILER_4=true -p:FABLE_COMPILER_JAVASCRIPT=true
      Determining projects to restore...
    src\App.csproj : error NU1605: Detected package downgrade: FSharp.Core from 6.0.0 to 4.7.2. Reference the package directly from the project to select a different version.
    src\App.csproj : error NU1605:  App -> Fable.Remoting.Client 7.26.0 -> Fable.Remoting.MsgPack 1.19.0 -> FSharp.Core (>= 6.0.0)
    src\App.csproj : error NU1605:  App -> Fable.Remoting.Client 7.26.0 -> FSharp.Core (>= 4.7.2)

Repro case is [here](https://github.com/brianberns/FableRemotingTest/tree/Fable4).

**Comment by Zaid-Ajaj** [comment]
Hi there @brianberns this is definitely not ideal, it seems to be that latest Fable.Remoting.MsgPack v1.19 is depending on FSharp.Core >= 6.0 but previous version v1.18 was correctly depending on FSharp.Core 4.7.2 so if you install Fable.Remoting.MsgPack v1.18 it should resolve this issue for now. 

I will publish a new version of MsgPack that depends on FSharp.Core 4.7.2

**Comment by Zaid-Ajaj** [comment]
Published a new batch of packages, Fable.Remoting.MsgPack v1.21 should now depend on FSharp.Core v4.7.2, just like Fable.Remoting.Client so that should fix your problem. Will close this issue as fixed, please re-open if the problem persists
