### ISSUE TITLE
ASP.NET Core sample not working out

### ISSUE THREAD

**Issue by nojaf** [Zaid-Ajaj/Fable.Remoting#63]
Hi, I'm trying to setup remoting with ASP.NET Core.

```fsharp
let remotingApp = 
    Remoting.createApi()
    |> Remoting.fromValue ronnyService
```

```
Value restriction. The value 'remotingApp' has been inferred to have generic type
    val remotingApp : RemotingOptions<'_a,Shared.Domain.IRonnyService>    
Either define 'remotingApp' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.
val remotingApp : RemotingOptions<obj,Shared.Domain.IRonnyService>
Full name: Ronnies.Server.Api.remotingApp
Assembly: Ronnies.Server
```

```fsharp
    let configureApp (app : IApplicationBuilder) =
        app.UseStaticFiles() 
        |>  fun a -> a.UseFreya (Api.webApp)
        |>  fun a -> a.UseRemoting(Api.remotingApp)
```

```fsharp
Type mismatch. Expecting a 'RemotingOptions<Http.HttpContext,'a>' but given a 'RemotingOptions<obj,Shared.Domain.IRonnyService>' The type 'Http.HttpContext' does not match the type 'obj'
```

What am I missing here?

**Comment by Zaid-Ajaj** [comment]
Hi there @nojaf, 

It seems that F# with cannot infer on it's own that `remotingApp` has type `RemotingOptions<HttpContext,  IRonnyService>` 

can you explicitly define `remotingApp` with that type? i.e. 
```fs
let remotingApp : RemotingOptions<HttpContext,  IRonnyService> = 
    Remoting.createApi()
    |> Remoting.fromValue ronnyService
```

**Comment by nojaf** [comment]
Adding the type resolves the problem, thanks for the quick response!

**Comment by Zaid-Ajaj** [comment]
No problem! :smile: 

On a side note, you actually don't need the explicit signature, F# should already infer the type when `remotingApp` was used in the function `UseRemoting`, I took a couple of minutes to make the simplest [pure kerstrel sample](https://github.com/Zaid-Ajaj/remoting-pure-kestrel), you can use it as a reference

**Comment by Zaid-Ajaj** [comment]
Alright then, I will add this as a side-note in the aspnet core docs 👌
