### ISSUE TITLE
Port Client to Fable 2.x

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#69]
Json serialization/deserialization should be almost ready from [Fable.SimpleJson](https://github.com/Zaid-Ajaj/Fable.SimpleJson), although there might be problems with recursive (self-referencing) types, I will need to check.

**Comment by nojaf** [comment]
Some errors I got during update to Fable2 beta:

```
Fable.Remoting.Client.3.2.0/Proxy.fs(130,32): (130,44) error FSHARP: The value or constructor 'ofJsonAsType' is not defined. Maybe you want one of the following:
   ofJson
 @ ./.fable/Fable.Remoting.Client.3.2.0/Remoting.fs 5:0-169 28:24-47 31:15-25 383:33-49
```

[Proxy.fs](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Client/Proxy.fs#L130)

```
/Fable.Remoting.Client.3.2.0/Proxy.fs(41,35): (41,41) error FABLE: Cannot get type info of generic parameter, please inline or inject a type resolver
 @ ./.fable/Fable.Remoting.Client.3.2.0/Remoting.fs 5:0-169 28:24-47 31:15-25 383:33-49
```

```
Fable.Remoting.Client.3.2.0/Remoting.fs(35,23): (35,29) error FABLE: Cannot get type info of generic parameter, please inline or inject a type resolver
```

How does `Simple.Json` and `Thoth` fit into this new Fable2 story? I thought Thoth is going to be the new default?

**Comment by Zaid-Ajaj** [comment]
Hello @nojaf, 
the errors you are getting are to be expected as Remoting.Client is not yet ported to Fable 2. It is not as simple as one would think, because Client relies *a lot* on internal Fable functionality for JSON marshalling (like `ofJsonAsType`) that is only usable from Fable 1. In fact, Fable 2 removed all JSON facilities and left reflection support available so that JSON marshalling can be done through third-party libraries like [Fable.SimpleJson](https://github.com/Zaid-Ajaj/Fable.SimpleJson) and [Thoth.Json](https://mangelmaxime.github.io/Thoth/index.html). These libraries are replacesments for `ofJson` and `toJson` from Fable plus some more functionality and features: 

- Fable.SimpleJson: Besides automatic JSON marshalling, treats JSON data as a document that you can pre-process (input JSON) and post-process (generated JSON)  like rewrite keys, capitalize string values, change date formats etc. You can also do manual serialization and deserialization with pattern matching. This one can be used only on the client in combination with the existing Fable.JsonConverter on the server. I began writing a pure .NET port of SimpleJson called [FSharp.SimpeJson](https://github.com/Zaid-Ajaj/FSharp.SimpleJson) but this one doesn't do automatic JSON marshalling yet.    

- Thoth.Json: same story with automatic JSON marshalling (although different implementation). Besides that, it is able to do manual JSON marshalling by composing decoders and encoders together to build bigger decoders and encoders etc. Inspired by Elm's way of dealing with JSON. This one can be used both on client and server. 

I hope this clears things up for you, let me know if you want to learn more :smile:

**Comment by nojaf** [comment]
Hi @Zaid-Ajaj , thanks for the explanation. So using `System.Reflection` or `FSharp.Reflection`  you need to provide `SimpleJson` or `Thoth` with enough info to get the serialization going?

Hmm that does sound tricky since the new api probably isn't really that documented yet.

**Comment by Zaid-Ajaj** [comment]
You don’t have to do anything with Reflection, the third-party libraries use reflection internally to implement JSON marshalling. For example, SimpleJson has this API:

let numbers = “[1, 2]” |> Json.parseAs<int list>

There are more functions available from SimpleJson for fine-grained control over JSON. Currently, most types can be converted back and forth except for recursive records (still working on that)

**Comment by nojaf** [comment]
I didn't mean `you` as consumer of Fable.Remoting. But more `you` as in a developer working on Fable.Remoting.

**Comment by Zaid-Ajaj** [comment]
Oh that, yeah it a bit tricky, hopefully SimpleJson already has everything I need for porting Client, both reflection abstractions and Json stuff so no worries for now :wink:

**Comment by Zaid-Ajaj** [comment]
Aaand just implemented support for recursive types in SimpleJson, Now Fable.Remoting will be able to support all types 😄 
```fs
type Recursive = {
    Name : string 
    Children : Recursive list
}

testCase "Recursive records can be converted" <| fun test ->
    let input = {
        Name = "root"
        Children = [ 
            { Name = "Child 1"; Children = [ { Name = "Grandchild 1"; Children = [ ] } ] }
            { Name = "Child 2"; Children = [ { Name = "Grandchild 2"; Children = [ ] } ] }
            { Name = "Child 2"; Children = [  ] }
        ]
    }

    input
    |> Json.stringify
    |> Json.parseAs<Recursive>
    |> test.areEqual input

type Tree = 
    | Leaf of int 
    | Branch of Tree * Tree 

testCase "Recursive unions can be converted" <| fun test ->
    let input = Branch(Branch(Leaf 10, Leaf 5), Leaf 5)
    
    input
    |> Json.stringify
    |> Json.parseAs<Tree>
    |> test.areEqual input
```

**Comment by nojaf** [comment]
Wow great news.

**Comment by Zaid-Ajaj** [comment]
Fixed in [https://github.com/Zaid-Ajaj/Fable.Remoting/pull/71](https://github.com/Zaid-Ajaj/Fable.Remoting/pull/71)

@nojaf The Fable client has been ported to Fable 2, published as verion `4.0.0-beta-001`, you will also need to update the server packages you are using because Json serialization on the server is updated as well to understand new representations of JSON from Fable 2 while being backwards-comaptible with Fable 1.x

**Comment by nojaf** [comment]
@Zaid-Ajaj thanks for releasing this so quickly. I've tested it just now and most things seem to work.

Except the following scenario:
```fsharp
type SecureResponse<'t> = Result<'t, AuthenticationError>

type IService = {
  getUsers: SecureRequest<unit> -> Async<SecureResponse<User list>>
}
```

The server is able to serialize this:
```json
{
    "Ok": [
        {
            "Login": "foo",
            "IsAdmin": false,
            "LastActivity": "2018-08-15T15:12:50.0379614Z"
        },
        {
            "Login": "bar",
            "IsAdmin": false,
            "LastActivity": "2018-08-09T18:48:07.0638391Z"
        }
    ]
}
```

but the client says:

```
UsersMsg RemotingFailure Error: Expected case 'Ok' to have 1 argument types but the JSON data only contained 2 values
String.js:200 remoting exn Error: Expected case 'Ok' to have 1 argument types but the JSON data only contained 2 values
```

**Comment by Zaid-Ajaj** [comment]
Nice catch! Fixed in SimpleJson and updated the remoting client, can you update to `4.0.0-beta-002` :smile:?

**Comment by nojaf** [comment]
@Zaid-Ajaj works like a charm. Many thanks for fixing this so quickly.

**Comment by Zaid-Ajaj** [comment]
Awesome! thanks for testing it out :smile: just please let me know if you encounter more of these types of errors
