### ISSUE TITLE
Should a request sent from client to server include browser cookies?

### ISSUE THREAD

**Issue by blair55** [Zaid-Ajaj/Fable.Remoting#7]
I'm observing that a Fable.Remoting RPC POST request to the (Suave) server does not include the Cookie header, so domain cookie values are not sent. This makes session management difficult.

I am wondering is this by design? Or perhaps an XMLHttpRequest restriction? I had thought you might not have to cater for this concept in the client lib at all, as the cookie header would be included automatically by the browser...?

What do you suggest?

**Comment by Zaid-Ajaj** [comment]
Hello @blair55, 
>I'm observing that a Fable.Remoting RPC POST request to the (Suave) server does not include the Cookie header, so domain cookie values are not sent. This makes session management difficult.

Indeed, this library only uses the request body data for communication. 

> I am wondering is this by design?

Not really, although it is recommended you use RPC for user authentication/session management with stateless tokens, there should be no restriction to use other machanisms like cookies assuming you are using this library as part of a bigger application. 

> as the cookie header would be included automatically by the browser...?

AFAIK the cookies should be sent along with the POST request automatically, but maybe since I am explicitly only using the body request, the cookies are ignored. 

>What do you suggest?

I will try to add the cookie header manually

**Comment by blair55** [comment]
Amazing, what a great response! I'm glad you could verify my thoughts.

Do you have an example of using stateless tokens with Fable.Remoting? I think I will stick with cookies if you can make it available, but would be good to appreciate the alternative.

Great library btw!
Thanks

**Comment by Zaid-Ajaj** [comment]
Thank you for your kind words :smile: 

I now have published a new version (1.4.0) of the Fable.Remoting.Client library where the browser cookies are included in the RPC request using the `Cookie` header with value `document.cookie`. I verified that it works on my integration tests project:

![screenshot from 2018-01-30 21-35-56](https://user-images.githubusercontent.com/13316248/35590768-18717a18-0608-11e8-8093-ea05ec4bb9ee.png)

Can you check that it works for you as well? 

> Do you have an example of using stateless tokens with Fable.Remoting?

Unfortunately, as of now, I do not have such example :( but I will try to put on together really soon when the time permits

**Comment by blair55** [comment]
Perfect! That's having the effect of sending the document cookie as expected.

Thanks for closing so quickly. Great work!

**Comment by Zaid-Ajaj** [comment]
Great, then this is resolved! I will close. Just let me know if you come across any issue :smile:
