### ISSUE TITLE
RemotingFailure Error: Cannot convert "JNull" to "Unit"

### ISSUE THREAD

**Issue by nojaf** [Zaid-Ajaj/Fable.Remoting#73]
Servers sends:
```
Fable.Remoting: Returning serialized result back to client
{"Ok":null}
```

And return type is 
```fsharp
type SecureResponse<'t> = Result<'t, AuthenticationError>
Async<SecureResponse<unit>>
```
`RemotingFailure Error: Cannot convert "JNull" to "Unit"`.
Using latest fable2 bits.

**Comment by Zaid-Ajaj** [comment]
Thanks for the report @nojaf, as a workaround for now, you can change unit to bool or int for example

I will try to fix it asap

**Comment by nojaf** [comment]
Thanks, it works now.
