### ISSUE TITLE
Using Fable.Remoting in multiple server scenarios

### ISSUE THREAD

**Issue by francotiveron** [Zaid-Ajaj/Fable.Remoting#78]
The documentation seems to show only examples where there is only one server, and client and server are in the same machine.
Is there an example where a client can call multiple different servers in different networked computers?
For example, how can I create multiple proxies in a client like in

let proxy1 = createApi("10.129.2.13")
let proxy2 = createApi("www.contoso.com")
let len1 = proxy1.getLength "String1"
let len2 = proxy2.getLength "String2"

**Comment by Zaid-Ajaj** [comment]
Hello there @francotiveron, a proxy by default will call the server of the same domain but you a different [base url](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.ClientV2/Remoting.fs#L20-L22) where the requests will be sent:
```fs
let musicStore : IMusicStore = 
  Remoting.createApi()
  |> Remoting.withBaseUrl "http://www.contoso.com"
  |> Remoting.buildProxy<IMusicStore>
```
I will add it to the docs soon-ish :smile:

**Comment by francotiveron** [comment]
Great, thanks
