### ISSUE TITLE
Async.Bind fails for remoting client if the protocol returns an array

### ISSUE THREAD

**Issue by theimowski** [Zaid-Ajaj/Fable.Remoting#83]
Given following sample:

Shared
```
namespace Shared

module Route =
    let builder typeName methodName =
        sprintf "/api/%s/%s" typeName methodName

type HighScore =
    { Name : string
      Score : int }

type IGameApi =
    { getHighScores : unit -> Async<HighScore array> }
```

Server (Saturn):
```
let getHighScores() : Task<_> =
    task {
        return
            [|
                { Name = "alfonsogarciacaro"; Score =  100 }
                { Name = "theimowski"; Score =  28 }
            |]
    }

let gameApi = {
    getHighScores = getHighScores >> Async.AwaitTask
}

let webApp =
    Remoting.createApi()
    |> Remoting.withRouteBuilder Route.builder
    |> Remoting.fromValue gameApi
    |> Remoting.buildHttpHandler

let app = application {
    url ("http://0.0.0.0:" + port.ToString() + "/")
    use_router webApp
    memory_cache
    use_static publicPath
    use_gzip
}

run app
```

and Client:
```
module Server =

    open Shared
    open Fable.Remoting.Client

    /// A proxy you can use to talk to server directly
    let api : IGameApi =
      Remoting.createApi()
      |> Remoting.withRouteBuilder Route.builder
      |> Remoting.buildProxy<IGameApi>

async {
    Browser.window.alert "before"
    let! scores = Server.api.getHighScores ()
    Browser.window.alert "after"
} |> Async.StartImmediate
```

The `after` msg does not appear in console.
If I change the protocol to return `HighScore` instead of `HighScore array`, the code works properly.

Edit: Just found that if I replace `HighScore array` with `HighScore list` the code works fine as well. So it seems it's just an issue with array.

**Comment by Zaid-Ajaj** [comment]
Thanks for the report @theimowski I am on it! 

Any chances you have the build versions for dotnet-fable, Fable.Core and remoting client?

**Comment by theimowski** [comment]
Sure thing:

```
Client dotnet-fable - 2.0.4
Client Fable.Core - 2.0
Client Fable.Remoting.Client - 4.2
Server Fable.Remoting.Giraffe - 3.4
Server FSharp.Core - 4.5.2
Server Saturn - 0.7.5
```

**Comment by Zaid-Ajaj** [comment]
@theimowski I am unable to reproduce the problem, I made tests [here](https://github.com/Zaid-Ajaj/Fable.Remoting/commit/13f5bc9467d69ade874f4473d23c3d4f93a19bd0) and [there](https://github.com/Zaid-Ajaj/Fable.Remoting/commit/3911cd2e805a2535e55e40de711aa081b699fc45) from your code and they are passing both locally and on CI, even added some [async tests](https://github.com/Zaid-Ajaj/Fable.SimpleJson/commit/76755291ad8de3e3d55d2bd4bf6fc4cf34eb967b) to SimpleJson but no luck

Would it be possible to make a repo/sample where the error is occuring? Also, does the code work with arrays if you add `do` keyword?

**Comment by theimowski** [comment]
Let me create a repro based on safe template (yet unreleased - the version with fable 2)

**Comment by theimowski** [comment]
Hm strange, tried to come up with minimal repro and I'm unable to reproduce. Maybe it had something to do with other parts of the larger app.. Closing, if I can come back to this then I'll reopen

**Comment by Zaid-Ajaj** [comment]
Oh yes, please re-open if the issue occurs again :smile:
