### ISSUE TITLE
Control serialization of payload

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.Remoting#87]
Fable.Remoting works really well for normal F# types (Records, Unions etc).

Is there a way to control serialization for more complex types?

---------------

I want to send geometric models from server to client.

My model looks like this:

```f#
type P = {
    Position: System.Numerics.Vector3
    Rotation: System.Numerics.Quaternion
}
```

On the server-side I use https://www.nuget.org/packages/System.Numerics.Vectors/.

On the client-side I added my own replacements which model the nuget package 1 : 1:

```f#
namespace rec System.Numerics

[<Struct>]
type Vector3(x : single, y : single, z : single) =

    new (value : single) = Vector3(value, value, value)

    member __.X = x
    member __.Y = y
    member __.Z = z

    // ...


[<Struct>]
type Quaternion(x : single, y : single, z : single, w : single) =
    
    new(vectorPart : Vector3, scalarPart : single) =
        Quaternion(vectorPart.X, vectorPart.Y, vectorPart.Z, scalarPart)

    member __.X = x
    member __.Y = y
    member __.Z = z
    member __.W = w

    // ...
```

Trying to send such an object over the wire fails:

```
"Cannot convert ["JObject",{"comparer":{},"tree":["MapNode","Y",["JNumber",0],["MapOne","X",["JNumber",0]],["MapOne","Z",["JNumber",0]],2]}] to ["Any",null]"
```

![grafik](https://user-images.githubusercontent.com/4236651/47739185-1831c780-dc75-11e8-9992-2f163005c4e0.png)

I've worked around this issue by just representing the vectors and quaternions as simple float arrays and then converting back and forth.

**Comment by Zaid-Ajaj** [comment]
Hello there @0x53A, 

> Is there a way to control serialization for more complex types?

I am afraid that customizing the serialization mechanism is not possible nor it is one of the goals of this library. 

> I've worked around this issue by just representing the vectors and quaternions as simple float arrays and then converting back and forth.

This is the way to go. if you want something slightly better than arrays, you can define a shared vector/quaternion types as records and convert them to your class types
