### ISSUE TITLE
Getting exception 'Refused to set unsafe header "Cookie"' after update to clientv2 version 4.5.0

### ISSUE THREAD

**Issue by nilekirk** [Zaid-Ajaj/Fable.Remoting#89]
The cookie is sent, though. So I think filtering out unsafe headers [here](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.ClientV2/Http.fs#L49) would solve the issue.

I'm on chrome latest. Havn't tested in other browsers.

**Comment by Zaid-Ajaj** [comment]
Hi there @nilekirk, I think this happens because I include `Cookie` [manually here](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.ClientV2/Proxy.fs#L72) where it should be sent automatically by the browser, I will investigate this further, thanks for repoting

**Comment by Zaid-Ajaj** [comment]
Just published the fix in v4.5.1 can you please update and check to see whether the issue if fixed?

**Comment by nilekirk** [comment]
It's working great. Thank you!

Also a big thank you for all your great libs! The whole team
here @UMCGlobalSafety sends their warmest regards.

All the best

Jonas

Den ons 7 nov. 2018 kl 15:37 skrev Zaid Ajaj <notifications@github.com>:

**Comment by Zaid-Ajaj** [comment]
Thank you Jonas! I am happy to hear that my libraries are being useful to you :heart:
