### ISSUE TITLE
Maps with record keys deserialization

### ISSUE THREAD

**Issue by cgravill** [Zaid-Ajaj/Fable.Remoting#91]
I've updated to a recent version of Fable.Remoting and am getting errors on deserialization. I've reduced the issue to maps with records as keys:

```fsharp
type ExampleRecord = {
    prop : int
}

type IServer = {
    recordKeyAPI : unit -> Async<Map<ExampleRecord, int>>
}

let server = {
    recordKeyAPI = fun() -> async { return Map.ofList [({prop = 2}, 3)] }
}
```
client:
```fsharp
try
    let! exampleCall = server.recordKeyAPI()
    printfn "%O" exampleCall
with ex ->
    console.error ex.Message

```
Then I get:
```
Cannot convert ["JString","{\"prop\":2}"] to ["Record",null]
```
Should that still work if I've got everything configured correctly?

Fable.Remoting.Client (4.5.1)
Fable.SimpleJson (2.6)

**Comment by Zaid-Ajaj** [comment]
Hello there @cgravill, I don't think I have covered such scenario but it I probably should support it, for now as a workaround you can use `(Record * int) list` until this is fixed

**Comment by cgravill** [comment]
Thanks for confirming @Zaid-Ajaj 

Yep, I'll probably do a workaround like that for now, there are quite a few nested maps on the API but it's straightforward.

**Comment by Zaid-Ajaj** [comment]
I just added the following test and it seems to work pass fine:
```
type RecordAsKey = { Key: int; Value : string }

testCase "Deserializing maps with record as key" <| fun test -> 
    [ { Key = 1; Value = "Value" }, 1 ]
    |> Map.ofList 
    |> Json.stringify 
    |> Json.parseNativeAs<Map<RecordAsKey, int>>
    |> Map.toList 
    |> function 
        | [ { Key = 1; Value = "Value" }, 1 ] -> test.pass()
        | otherwise -> test.unexpected otherwise
```
Do you happen to have a more complex sample that doesn't work? 
And most importantly, are you using latest `dotnet-fable`?

**Comment by cgravill** [comment]
Thanks! I started looking at the `MapSerializer` implementation but wasn't sure how that connects up to the client-side bit.

**Comment by Zaid-Ajaj** [comment]
The fix is published with v4.5.2, can you please update to check whether the issue persists?

**Comment by cgravill** [comment]
Thanks, that did it and my app is fully working on Fable 2.x now!

**Comment by Zaid-Ajaj** [comment]
@cgravill Happy to hear that :smile:

**Comment by cgravill** [comment]
Incidentally, Fable.Remoting has been very helpful for getting some tools up and running quickly. Many thanks for building it and continuing to develop it with the Fable 2.x changes.
