### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by ikzk** [Zaid-Ajaj/Fable.Remoting#94]
It seems that in the readme, the following example code has an extra `()`

```fsharp
open SharedTypes

let getStudents() = async {
    return [
        { Name = "Mike";  Age = 23; }
        { Name = "John";  Age = 22; }
        { Name = "Diana"; Age = 22; }
    ]
}

let findStudentByName name = async {
    let! students = getStudents() 
    let student = List.tryFind (fun student -> student.Name = name) students
    return student 
}

let studentApi : IStudentApi = {
    studentByName = findStudentByName
    allStudents = getStudents()  // shouldn't have () here
}
```

**Comment by Zaid-Ajaj** [comment]
Hello @ikzk, thanks for checking the readme, but this is not a typo, the record field `allStudents` has type `Async<Student list>`, so I need to evaluate `getStudents` when constructing the record field  

If `allStudents` had the type `unit -> Async<Student list>` then I wouldn't need to use `()` but that is not the case here, see for yourself that this actually compiles in [this dotnet fiddle sample](https://dotnetfiddle.net/MRwBhx)

**Comment by ikzk** [comment]
Gotcha. Thanks for your comments!
