### ISSUE TITLE
TypeError: $x$$3.CompareTo is not a function

### ISSUE THREAD

**Issue by vasily-kirichenko** [Zaid-Ajaj/Fable.Remoting#99]
I have `TypeError: $x$$3.CompareTo is not a function` receiving a list of records.

The record contains string and lists of other records, all of them contains fields of primitive types only, no `Set`s or `Map`s.

I turn on the diagnostics on server and it wrote it sent completely nice JSON to the client. 

How to diagnose this error further?

**Comment by vasily-kirichenko** [comment]
The error has gone after restarting server and client.

**Comment by Zaid-Ajaj** [comment]
Hello @vasily-kirichenko, it looks like the cached assets: `obj` and `bin` are interfering with the compilation. We have seen this before in Fable, restarting the compilation process should fix it. 

> How to diagnose this error further?

Usually this should not happen, but if it does, then it is either that the server is sending weird JSON or that the client cannot deserialize, is which case you can try using `Fable.SimpleJson` standalone (included in the remoting client) to deserialize the incoming json: `Json.parseNativeAs<Type>(jsonContent)`

**Comment by vasily-kirichenko** [comment]
Thank you, will know how to deal with it in the future :)
